---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
     user_name: obed2023
  ignore_errors: true   
  tasks:
    - name: Install softwares
      package: 
        state: present
        name: "{{ item }}"
      loop:
        -wget
        -finger
        -curl
        -ntp
    - name: install passwd
      apt: 
         name: passwd
         state: present
      when: ansible_distribution in "Debian, Ubuntu"
      tags:
        - app1

    - name: create group
      group:
         name: cloudteam
         state: present
    - name: create user
      user:
          name: "{{user_name}}"
          comment: Obed Admin
          group: cloudteam   

- hosts: databaseservers
  become: yes          
  tasks:
      - name: install apache
        apt:
          name: apache2
          state: present
      - name: start apache service
        service: name=apache2 state=started enabled=yes
        tags: 
          - service
      - name: copy index file 
        copy: 
          src: index.html
          dest: /var/www/html/index.html
          mode: '0644'